### ISSUE TITLE
Ошибка проверки md-standard-attribute-synonym-empty на проекте расширения

### ISSUE THREAD

**Issue by vadimeg** [1C-Company/v8-code-style#1021]
### Описание ошибки

NullPointerException на валидации проекта-расширения, у которого не выставлен defaultLanguage

### Как воспроизвести

За базовый проект возьмите типовую БП последней версии. Расширение **Smartegra**. На нем не выставлен defaulLanguage. На валидации расширения получаем NPE.

### Ожидаемое поведение

Проверка должна отрабатывать без ошибок

### Лог рабочей области

```
!ENTRY com.e1c.g5.v8.dt.check 4 0 2022-04-21 20:56:14.461
!MESSAGE Validation check thrown an exception (monitor cancellation state is false): 
!STACK 0
java.lang.NullPointerException
	at com.e1c.v8codestyle.md.check.MdStandardAttributeSynonymEmpty.check(MdStandardAttributeSynonymEmpty.java:110)
	at com.e1c.g5.v8.dt.check.components.BasicCheck.check(BasicCheck.java:76)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.validateModel(CheckExecutor.java:298)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.check(ModelCheckDerivedDataComputer.java:134)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.doFullRebuildForObject(ModelCheckDerivedDataComputer.java:238)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.doFullRebuild(ModelCheckDerivedDataComputer.java:173)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer$1.execute(ModelCheckDerivedDataComputer.java:108)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer$1.execute(ModelCheckDerivedDataComputer.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com.e1c.g5.v8.dt.internal.check.derived.ModelCheckDerivedDataComputer.compute(ModelCheckDerivedDataComputer.java:114)
```

### Версия 1С:Code style V8

edt-2022-1

### Версия 1С:EDT

Ruby 2022.1

### Операционная система

Windows

**Comment by marmyshev** [comment]
https://github.com/1C-Company/v8-code-style/issues/1021 дубль
