### ISSUE TITLE
Internal error при сортировке метаданных

### ISSUE THREAD

**Issue by vadimeg** [1C-Company/v8-code-style#1449]
### Описание ошибки

Ломается сортировка после переоткрытия или пересоздания проекта

### Как воспроизвести

- Создать конфигурацию Configuration1
- Добавить справочник
- Закрыть, удалить или поклинить конфигурацию
- Переоткрыть или создать новую конфигурацию с тем же именем или дождаться открытия конфигурации после клина
- Создать еще один справочник

### Ожидаемое поведение

Сортировка не должна ломаться

### Лог рабочей области

```
!ENTRY org.eclipse.core.jobs 4 2 2024-06-05 18:49:15.982
!MESSAGE An internal error occurred during: "Sort metadata objects: Configuration1".
!STACK 0
java.lang.IllegalStateException: The project 'Configuration1' is not registered
    at com._1c.g5.v8.dt.internal.core.operations.pipeline.ProjectOrchestrator.requireProjectInfo(ProjectOrchestrator.java:1067)
    at com._1c.g5.v8.dt.internal.core.operations.pipeline.ProjectOrchestrator.enqueueOperation(ProjectOrchestrator.java:697)
    at com._1c.g5.v8.dt.internal.core.operations.pipeline.ProjectOrchestrator.enqueueOperation(ProjectOrchestrator.java:667)
    at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.enqueueHalfExclusiveOperation(WorkspaceOrchestrator.java:545)
    at com._1c.g5.v8.dt.internal.core.platform.WorkspaceOrchestrator.beginHalfExclusiveOperation(WorkspaceOrchestrator.java:586)
    at com._1c.g5.v8.dt.core.platform.IWorkspaceOrchestrator$pbryglu.beginHalfExclusiveOperation(Unknown Source)
    at com.e1c.v8codestyle.internal.autosort.SortJob.execute(SortJob.java:108)
    at com.e1c.v8codestyle.internal.autosort.SortJob.run(SortJob.java:82) 
```

### Версия 1С:Code style V8

edt-2024-1

### Версия 1С:EDT

Ruby 2024.1

### Операционная система

Windows

**Comment by vadimeg** [comment]
Исправлено в 2024.1
