### ISSUE TITLE
Исключение проверки ((QueryInLoopCheck.java:291))

### ISSUE THREAD

**Issue by Desar14** [1C-Company/v8-code-style#830]
## Опишите ошибку

В логах ошибка java.lang.NullPointerException

## Скриншоты

![image](https://user-images.githubusercontent.com/66671103/136393156-f8d33718-e665-44fa-abd1-6e0336fad291.png)

## Окружение (пожалуйста укажите информацию):

 - OS: Win10
 - Версия 1C:Code-Style-V8 1С:Стандарты разработки V8 0.1.0.126
 - Версия 1C:EDT Ruby 2021.2.6

## Дополнительная информация
java.lang.NullPointerException
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1224)
	at java.base/java.lang.String$CaseInsensitiveComparator.compare(String.java:1218)
	at java.base/java.util.TreeMap.getEntryUsingComparator(TreeMap.java:374)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:343)
	at java.base/java.util.TreeMap.containsKey(TreeMap.java:231)
	at java.base/java.util.TreeSet.contains(TreeSet.java:234)
	at com.e1c.v8codestyle.bsl.check.QueryInLoopCheck.isQueryExecution(QueryInLoopCheck.java:229)
	at com.e1c.v8codestyle.bsl.check.QueryInLoopCheck.getMethodsWithQuery(QueryInLoopCheck.java:291)
	at com.e1c.v8codestyle.bsl.check.QueryInLoopCheck.check(QueryInLoopCheck.java:140)
	at com.e1c.g5.v8.dt.check.components.BasicCheck.check(BasicCheck.java:76)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.runLanguageChecks(CheckExecutor.java:679)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.validateLanguage(CheckExecutor.java:209)
	at com.e1c.g5.v8.dt.internal.check.bsl.BslValidationContributor.validate(BslValidationContributor.java:159)
	at com._1c.g5.v8.dt.bsl.validation.IBslValidationContributor$pbryglu.validate(Unknown Source)
	at com._1c.g5.v8.dt.bsl.validation.ExternalValidatorServiceProvider.validate(ExternalValidatorServiceProvider.java:75)
	at com._1c.g5.v8.dt.bsl.validation.BslCancelableDiagnostician.doValidateContents(BslCancelableDiagnostician.java:168)
	at com._1c.g5.modeling.xtext.validation.CustomCancelableDiagnostician.validate(CustomCancelableDiagnostician.java:71)
	at com._1c.g5.modeling.xtext.validation.CustomCancelableDiagnostician.validate(CustomCancelableDiagnostician.java:84)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:142)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:147)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:125)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com._1c.g5.v8.dt.lcore.validation.NotifyingResourceValidator.validate(NotifyingResourceValidator.java:51)
	at com._1c.g5.v8.dt.bsl.validation.BslNotifyingResourceValidator.validate(BslNotifyingResourceValidator.java:98)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocumentProvider$BslValidationJob$1$2.execute(BslXtextDocumentProvider.java:391)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocumentProvider$BslValidationJob$1$2.execute(BslXtextDocumentProvider.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocumentProvider$BslValidationJob$1.exec(BslXtextDocumentProvider.java:385)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocumentProvider$BslValidationJob$1.exec(BslXtextDocumentProvider.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocument$CustomXtextDocumentLocker.internalReadOnly(BslXtextDocument.java:538)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocument$CustomXtextDocumentLocker.readOnly(BslXtextDocument.java:429)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at com._1c.g5.v8.dt.bsl.ui.editor.BslXtextDocumentProvider$BslValidationJob.createIssues(BslXtextDocumentProvider.java:336)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63
[лог файл.log](https://github.com/1C-Company/v8-code-style/files/7303655/default.log)
)

**Comment by Desar14** [comment]
опять есть исключение

java.lang.NullPointerException
	at com.e1c.v8codestyle.bsl.check.QueryInLoopCheck.getMethodsWithQuery(QueryInLoopCheck.java:298)
	at com.e1c.v8codestyle.bsl.check.QueryInLoopCheck.check(QueryInLoopCheck.java:140)
	at com.e1c.g5.v8.dt.check.components.BasicCheck.check(BasicCheck.java:76)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.runLanguageChecks(CheckExecutor.java:679)
	at com.e1c.g5.v8.dt.internal.check.CheckExecutor.validateLanguage(CheckExecutor.java:209)
	at com.e1c.g5.v8.dt.internal.check.bsl.BslValidationContributor.validate(BslValidationContributor.java:159)
	at com._1c.g5.v8.dt.bsl.validation.IBslValidationContributor$pbryglu.validate(Unknown Source)
	at com._1c.g5.v8.dt.bsl.validation.ExternalValidatorServiceProvider.validate(ExternalValidatorServiceProvider.java:75)
	at com._1c.g5.v8.dt.bsl.validation.BslCancelableDiagnostician.doValidateContents(BslCancelableDiagnostician.java:168)
	at com._1c.g5.modeling.xtext.validation.CustomCancelableDiagnostician.validate(CustomCancelableDiagnostician.java:71)
	at com._1c.g5.modeling.xtext.validation.CustomCancelableDiagnostician.validate(CustomCancelableDiagnostician.java:84)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:142)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:147)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:125)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:91)
	at com._1c.g5.v8.dt.lcore.validation.NotifyingResourceValidator.validate(NotifyingResourceValidator.java:51)
	at com._1c.g5.v8.dt.bsl.validation.BslNotifyingResourceValidator.validate(BslNotifyingResourceValidator.java:98)
	at com._1c.g5.v8.dt.internal.bsl.bm.ui.deepanalysis.BslDeepAnalisysService.performXtextResourceValidation(BslDeepAnalisysService.java:421)
	at com._1c.g5.v8.dt.internal.bsl.bm.ui.deepanalysis.BslDeepAnalisysService$3.execute(BslDeepAnalisysService.java:235)
	at com._1c.g5.v8.dt.internal.bsl.bm.ui.deepanalysis.BslDeepAnalisysService$3.execute(BslDeepAnalisysService.java:1)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:706)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeTask(Reactor.java:667)
	at com._1c.g5.v8.bm.integration.internal.reactor.Reactor.executeReadOnlyTask(Reactor.java:146)
	at com._1c.g5.v8.bm.integration.internal.BmModel.executeReadonlyTask(BmModel.java:227)
	at com._1c.g5.v8.dt.internal.bsl.bm.ui.deepanalysis.BslDeepAnalisysService.performDeepAnalisys(BslDeepAnalisysService.java:197)
	at com._1c.g5.v8.dt.bsl.validation.IBslDeepAnalisysService$pbryglu.performDeepAnalisys(Unknown Source)
	at com.e1c.g5.v8.dt.internal.check.derived.LanguageCheckDerivedDataComputer.compute(LanguageCheckDerivedDataComputer.java:96)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.processContextBatch(WorkerManager.java:330)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.call(WorkerManager.java:165)
	at com._1c.g5.v8.internal.derived.WorkerManager$TaskProcessor.call(WorkerManager.java:1)
	at com._1c.g5.v8.internal.derived.scheduler.DerivedDataExecutorPool$2.get(DerivedDataExecutorPool.java:256)
	at com._1c.g5.v8.internal.derived.scheduler.DerivedDataExecutorPool$2.get(DerivedDataExecutorPool.java:1)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
